<a href="https://colab.research.google.com/github/naoki-yoshi/Task/blob/master/task_7gyouretuseki.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 【問題1】行列積を手計算する

In [ ]:
import numpy as np

In [ ]:
a_ndarray = np.array([[-1,2,3],[4,-5,6],[7,8,-9]])
b_ndarray = np.array([[0,2,1],[0,2,-8],[2,9,-1]])

In [ ]:
a_ndarray

array([[-1,  2,  3],
       [ 4, -5,  6],
       [ 7,  8, -9]])

In [ ]:
b_ndarray 

array([[ 0,  2,  1],
       [ 0,  2, -8],
       [ 2,  9, -1]])

In [ ]:
a = a_ndarray
b = b_ndarray 

In [ ]:
a[2,0]*b[0,0] + a[2,1]*b[1,0] + a[2,2]*b[2,0]

-18

In [ ]:
b[0,1]

2

In [ ]:
ab_ndarray = np.array([[a[0,0]*b[0,0] + a[0,1]*b[1,0] + a[0,2]*b[2,0],
                       a[0,0]*b[0,1] + a[0,1]*b[1,1] + a[0,2]*b[2,1],
                       a[0,0]*b[0,2] + a[0,1]*b[1,2] + a[0,2]*b[2,2]],
                       [a[1,0]*b[0,0] + a[1,1]*b[1,0] + a[1,2]*b[2,0],
                       a[1,0]*b[0,1] + a[1,1]*b[1,1] + a[1,2]*b[2,1],
                       a[1,0]*b[0,2] + a[1,1]*b[1,2] + a[1,2]*b[2,2]],
                       [a[2,0]*b[0,0] + a[2,1]*b[1,0] + a[2,2]*b[2,0],
                       a[2,0]*b[0,1] + a[2,1]*b[1,1] + a[2,2]*b[2,1],
                       a[2,0]*b[0,2] + a[2,1]*b[1,2] + a[2,2]*b[2,2]],
                      ])
ab_ndarray

array([[  6,  29, -20],
       [ 12,  52,  38],
       [-18, -51, -48]])


## 【問題2】NumPyの関数による計算

np.matmulにて計算

In [ ]:
np.matmul(a_ndarray,b_ndarray)

array([[  6,  29, -20],
       [ 12,  52,  38],
       [-18, -51, -48]])

In [ ]:
np.matmul(b_ndarray,a_ndarray) # BA

array([[ 15,  -2,   3],
       [-48, -74,  84],
       [ 27, -49,  69]])

np.dotにて計算

In [ ]:
np.dot(a_ndarray,b_ndarray)

array([[  6,  29, -20],
       [ 12,  52,  38],
       [-18, -51, -48]])

In [ ]:
np.dot(b_ndarray,a_ndarray) #BA

array([[ 15,  -2,   3],
       [-48, -74,  84],
       [ 27, -49,  69]])

＠にて計算

In [ ]:
a_ndarray@b_ndarray

array([[  6,  29, -20],
       [ 12,  52,  38],
       [-18, -51, -48]])

In [ ]:
b_ndarray@a_ndarray # BA

array([[ 15,  -2,   3],
       [-48, -74,  84],
       [ 27, -49,  69]])

## 【問題3】ある要素の計算を実装

numpy配列にて計算

行列Aの０行目と行列Bの１列目を掛け合わせて、その後合計する

In [ ]:
mat00 = (a_ndarray[0]*b_ndarray[:,0]).sum()
print("行列Aの０行目と行列Bの０列目の合計は{}".format(mat00))

行列Aの０行目と行列Bの０列目の合計は6


## 【問題4】行列積を行う関数の作成

In [ ]:
def mat (a,b):
    """"    
行列積を行う関数　
Parameters
----------------
a, b : ndarray
AとBに対応する行列
Returns
 ----------------
c  : ndarray
計算した行列積
  """ 
    c = np.empty((a.shape[0],b.shape[1]))
    for x in range(a.shape[0]):
        for y in range(b.shape[1]):
            c[x,y] = (a[x,:] * b[:,y]).sum()
    return c

a_ndarray = np.array([[-1,2,3],[4,-5,6],[7,8,-9]])
b_ndarray = np.array([[0,2,1],[0,2,-8],[2,9,-1]])
 
mat(a_ndarray,b_ndarray)

array([[  6.,  29., -20.],
       [ 12.,  52.,  38.],
       [-18., -51., -48.]])

##  【問題5】計算が定義されない入力を判定する

関数にif文を追加する

In [ ]:
def mat (a,b):
    """"    
行列積を行う関数　
Parameters
----------------
a, b : ndarray
AとBに対応する行列
Returns
 ----------------
c  : ndarray
計算した行列積
  """ 
    if a.shape[1] == b.shape[0] :
        
        c = np.empty((a.shape[0],b.shape[1]))
        for x in range(a.shape[0]):
            for y in range(b.shape[1]):
                c[x,y] = (a[x,:] * b[:,y]).sum()
        return c
    
    else :
        return print("Aの列数とBの行数が等しくないので計算できない")
        

a_ndarray = np.array([[-1,2,],[4,-5,]])
b_ndarray = np.array([[0,2,1],[0,2,-8],[2,9,-1]])
 
mat(a_ndarray,b_ndarray)

Aの列数とBの行数が等しくないので計算できない


##  【問題6】転置

In [ ]:
d_ndarray = np.array([[2,4,6],[3,5,6]])
e_ndarray = np.array([[4,5,6],[1,3,5]])

In [ ]:
d_ndarray

array([[2, 4, 6],
       [3, 5, 6]])

In [ ]:
e_ndarray

array([[4, 5, 6],
       [1, 3, 5]])

In [ ]:
# d_ndarrayを転置する
f_ndarray = np.transpose(d_ndarray)

In [ ]:
f_ndarray

array([[2, 3],
       [4, 5],
       [6, 6]])

In [ ]:
np.matmul(f_ndarray,e_ndarray)

array([[11, 19, 27],
       [21, 35, 49],
       [30, 48, 66]])